config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views


urlpatterns = [
    path("", include("prospector.apps.questionnaire.urls")),
    path("accounts/", include("prospector.apps.users.urls")),
    # Has to go above the main admin bit
    path(f"{settings.ADMIN_URL}django-rq/", include("django_rq.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

prospector/apps/questionnaire/urls.py
from django.urls import path

from .views import trail as views

app_name = "questionnaire"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("start", views.Start.as_view(), name="start"),
    path("name", views.RespondentName.as_view(), name="respondent-name"),
    path("role", views.RespondentRole.as_view(), name="respondent-role"),
    path(
        "consent",
        views.RespondentHasPermission.as_view(),
        name="respondent-has-permission",
    ),
    path(
        "will-to-contribute",
        views.WillToContribute.as_view(),
        name="will-to-contribute",
    ),
    path("company-name", views.CompanyName.as_view(), name="company-name"),
    path(
        "your-postcode", views.RespondentPostcode.as_view(), name="respondent-postcode"
    ),
    path("your-address", views.RespondentAddress.as_view(), name="respondent-address"),
    path("your-email", views.Email.as_view(), name="email"),
    path("phone-numbers", views.ContactPhone.as_view(), name="contact-phone"),
    path("occupant-name", views.OccupantName.as_view(), name="occupant-name"),
    path(
        "property-postcode", views.PropertyPostcode.as_view(), name="property-postcode"
    ),
    path("property-address", views.PropertyAddress.as_view(), name="property-address"),
    path("address-unknown", views.AddressUnknown.as_view(), name="address-unknown"),
    path("thank-you", views.ThankYou.as_view(), name="thank-you"),
    path("property-tenure", views.Tenure.as_view(), name="tenure"),
    path("consents", views.Consents.as_view(), name="consents"),
    path(
        "property-summary",
        views.PropertyMeasuresSummary.as_view(),
        name="property-measures-summary",
    ),
    path("occupants", views.Occupants.as_view(), name="occupants"),
    path(
        "means-tested-benefits",
        views.MeansTestedBenefits.as_view(),
        name="means-tested-benefits",
    ),
    path(
        "past-means-tested-benefits",
        views.PastMeansTestedBenefits.as_view(),
        name="past-means-tested-benefits",
    ),
    path("income", views.HouseholdIncome.as_view(), name="household-income"),
    path(
        "after-tax-income",
        views.HouseholdIncomeAfterTax.as_view(),
        name="household-income-after-tax",
    ),
    path("housing-costs", views.HousingCosts.as_view(), name="housing-costs"),
    path(
        "disability-benefits",
        views.DisabilityBenefits.as_view(),
        name="disability-benefits",
    ),
    path("child-benefit", views.ChildBenefit.as_view(), name="child-benefit"),
    path(
        "child-benefit-number",
        views.ChildBenefitNumber.as_view(),
        name="child-benefit-number",
    ),
    path(
        "child-benefit-claimant-type",
        views.ChildBenefitClaimantType.as_view(),
        name="child-benefit-claimant-type",
    ),
    path(
        "free-school-meals-eligibility",
        views.FreeSchoolMealsEligibility.as_view(),
        name="free-school-meals-eligibility",
    ),
    path(
        "vulnerabilities-general",
        views.VulnerabilitiesGeneral.as_view(),
        name="vulnerabilities-general",
    ),
    path("vulnerabilities", views.Vulnerabilities.as_view(), name="vulnerabilities"),
    path(
        "council-tax-reduction",
        views.CouncilTaxReduction.as_view(),
        name="council-tax-reduction",
    ),
    path("answers-summary", views.AnswersSummary.as_view(), name="answers-summary"),
    path("energy-advices", views.EnergyAdvices.as_view(), name="energy-advices"),
    path(
        "recommended-measures",
        views.RecommendedMeasures.as_view(),
        name="recommended-measures",
    ),
]

prospector/apps/users/urls.py
from django.urls import include
from django.urls import path

urlpatterns = [path("", include("django.contrib.auth.urls"))]

prospector/apps/crm/models.py
from django.db import models

from prospector.apps.questionnaire.models import Answers


class CrmState(models.TextChoices):
    SUCCESS = "SUCCESS", "Status Success"
    FAILURE = "FAILURE", "Status Failure"


class CrmResult(models.Model):
    answers = models.ForeignKey(Answers, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    state = models.CharField(
        max_length=32, choices=CrmState.choices, db_index=True, blank=True
    )
    result = models.JSONField(null=True)

prospector/apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

prospector/apps/questionnaire/views/abstract.py
import contextlib
import logging
from enum import auto
from enum import Enum
from typing import Optional

from crispy_forms_gds.helper import FormHelper
from crispy_forms_gds.layout import Field
from crispy_forms_gds.layout import Layout
from crispy_forms_gds.layout import Size
from django import forms
from django.views.generic.edit import FormView

from prospector.apps.questionnaire import forms as questionnaire_forms
from prospector.apps.questionnaire import models
from prospector.trail import mixin

logger = logging.getLogger(__name__)


SESSION_ANSWERS_ID = "questionnaire:answer_id"
SESSION_TRAIL_ID = "questionnaire:trail_id"


class QuestionType(Enum):
    Int = auto()
    Text = auto()
    YesNo = auto()
    Decimal = auto()
    Choices = auto()
    MultipleChoices = auto()


class Question(mixin.TrailMixin, FormView):
    """The custom trail class for the whole survey."""

    trail_initial = ["Start"]

    trail_session_id = SESSION_TRAIL_ID
    trail_url_prefix = "questionnaire:"
    form_class = questionnaire_forms.DummyForm

    def _init_answers(self):
        # Don't let us get called more than once.
        if hasattr(self, "answers"):
            return

        self.answers = None
        if SESSION_ANSWERS_ID in self.request.session:
            with contextlib.suppress(models.Answers.DoesNotExist):
                self.answers = models.Answers.objects.filter(
                    id=self.request.session[SESSION_ANSWERS_ID],
                    completed_at__isnull=True,
                ).first()

        if not self.answers:
            self.answers = models.Answers.objects.create()
            self.request.session[SESSION_ANSWERS_ID] = self.answers.id

            # if we had a trail, wipe it, forcing us back to the start.
            if SESSION_TRAIL_ID in self.request.session:
                del self.request.session[SESSION_TRAIL_ID]

    def dispatch(self, request, *args, **kwargs):
        self._init_answers()
        return super().dispatch(request, *args, **kwargs)

    # Make the answers accessible to the form logic
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["answers"] = self.answers
        return kwargs

    def get_initial(self):
        # Populate form fields from model first.
        # This will need to be overridden if non-model form fields are present
        data = {}

        # Do we have any model form fields in the form?
        form_class = self.get_form_class()
        if hasattr(form_class, "_meta"):
            for field in self.get_form_class()._meta.fields:
                if hasattr(self.answers, field):
                    data[field] = getattr(self.answers, field)
        return data

    def form_valid(self, form):
        """
        Save form fields to the answers.

        Fields that match Answers fields will be saved, anything else discarded.
        """
        for k, v in form.cleaned_data.items():
            setattr(self.answers, k, v)

        # This gives questions an opportunity to do extra processing, lookups etc.
        # before we save, saving unnecessary round trips to the database.
        if hasattr(self, "pre_save"):
            self.pre_save()

        self.answers.save()

        return self.redirect(self.get_next())

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["prev_url"] = self.get_prev_url()
        context["title"] = self.get_title()
        context["percent_complete"] = self.get_percent_complete()

        return context

    def get_title(self):
        """Get a page title for the HTML <title> tag."""

        if hasattr(self, "title"):
            return self.title

        return self.__class__.__name__

    def get_percent_complete(self) -> int:
        return getattr(self, "percent_complete", 0)


class NoQuestion(Question):
    """Produces a non-question view, e.g. summary or info view."""

    type_: QuestionType
    question: None
    next: str


class SingleQuestion(Question):
    """
    Produces a 'standard' single question view.

    This uses a load of metaprogramming to make the question definitions as simple
    and concise as possible, meaning that a separate form class definition is
    not required this view. It inherits from the Question class above.
    """

    type_: QuestionType
    question: str
    supplementary: Optional[str]
    note: Optional[str]
    unit: Optional[str]
    next: Optional[str]
    icon: Optional[str]

    template_name = "questionnaire/single_question.html"

    def _type_to_field(self):
        if self.type_ is QuestionType.Int:
            return forms.IntegerField(required=True)
        elif self.type_ is QuestionType.Text:
            return forms.CharField(required=True)
        elif self.type_ is QuestionType.YesNo:
            # https://code.djangoproject.com/ticket/2723#comment:18
            return forms.TypedChoiceField(
                coerce=lambda x: x == "True",
                choices=self.get_choices(),
                widget=forms.RadioSelect,
                required=True,
            )
        elif self.type_ is QuestionType.Decimal:
            return forms.DecimalField(required=True)
        elif self.type_ is QuestionType.Choices:
            return forms.ChoiceField(
                widget=forms.RadioSelect, required=True, choices=self.get_choices()
            )
        elif self.type_ is QuestionType.MultipleChoices:
            return forms.MultipleChoiceField(
                widget=forms.CheckboxSelectMultiple,
                required=False,
                choices=self.get_choices(),
            )
        else:
            raise NotImplementedError(f"{self.type_} not implemented")

    def get_form_class(self):
        this = self

        def clean_field(self):
            data = self.cleaned_data["field"]
            if hasattr(this, "validate_answer"):
                this.validate_answer(data)
            return data

        # Instead of defining a separate form for each page, which is repetitious,
        # difficult to maintain, and splits forms and views that are intimately related
        # across files, we instead specify a limited number of question types.
        #
        # Each question view has one type, and we generate the form dynamically here.
        QuestionForm = type(
            "QuestionForm",
            (questionnaire_forms.AnswerFormMixin, forms.Form),
            {"field": self._type_to_field(), "clean_field": clean_field},
        )

        return QuestionForm

    def get_choices(self):
        # This is overridable for when we want to provide dynamic choices.
        if self.type_ is QuestionType.YesNo and not hasattr(self, "choices"):
            # Default for Yes/No field
            return ((True, "Yes"), (False, "No"))
        return self.choices

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["question_text"] = self.get_question()

        context["question_supplement"] = self.get_supplementary()
        if hasattr(self, "unit"):
            context["unit"] = self.unit
        context["question_note"] = self.get_note()
        if hasattr(self, "icon"):
            context["question_icon"] = self.icon
        return context

    def get_answer_field(self):
        """
        Return the name of the field that contains the answer to this question.

        Normally we generate this automatically from the class name - so a class
        LivesInGermany will look for the answer in lives_in_germany.  However, there
        are times when you want to override this - you can do this by specifying
        answer_field on the class, or by overriding this function if you need more
        dynamic behaviour.
        """
        if hasattr(self, "answer_field"):
            return self.answer_field
        else:
            return mixin.snake_case(self.__class__.__name__, separator="_")

    def get_initial(self, *args, **kwargs):
        return {"field": getattr(self.answers, self.get_answer_field())}

    def sanitise_answer(self, data):
        """
        Sanitise the data received in some way.

        Override this when you need to normalise incoming data in some way.
        """
        return data

    def get_question(self):
        """Override this to set the question text dynamically."""
        if hasattr(self, "question"):
            return self.question

    def get_supplementary(self):
        """Override this to set the supplementary text dynamically."""
        if hasattr(self, "supplementary"):
            return self.supplementary

    def get_note(self):
        """Override this to set notes dynamically."""
        if hasattr(self, "note"):
            return self.note

    def form_valid(self, form):
        sanitised = self.sanitise_answer(form.cleaned_data["field"])
        field_name = self.get_answer_field()
        setattr(self.answers, field_name, sanitised)

        # This gives questions an opportunity to do extra processing, lookups etc.
        # before we save, saving unnecessary round trips to the database.
        if hasattr(self, "pre_save"):
            self.pre_save()

        self.answers.save()

        return self.redirect(self.get_next())


class SinglePrePoppedQuestion(SingleQuestion):
    """
    A 'standard' single question view with a value presented from third party property data.

    Mirrors the PrePoppedMixin for forms. Adds in a 'data_correct' boolean field
    and uses the data field value as the initial field value (if no value for the
    field already) as well as putting it into context.
    """

    template_name = "questionnaire/single_prepopped_question.html"

    def get_form_class(self):
        this = self

        def clean_field(self):
            data = self.cleaned_data["field"]
            if hasattr(this, "validate_answer"):
                this.validate_answer(data)

prospector/templates/questionnaire/includes/gas_boiler_present.html
<tr>
    <td>Does the property have a hot water storage tank?</td>
    <td>{{ user_data.hwt_present|yesno|capfirst }}</td>
    <td><a href='{% url "questionnaire:hwt-present" %}'>CHANGE</a></td>
</tr>
<tr>
    <td>When was the current boiler installed?</td>
    <td>{{ user_data.gas_boiler_age }}</td>
    <td><a href='{% url "questionnaire:gas-boiler-age" %}'>CHANGE</a></td>
</tr>
<tr>
    <td>Is the gas boiler currently broken?</td>
    <td>{{ user_data.gas_boiler_broken|yesno|capfirst }}</td>
    <td><a href='{% url "questionnaire:gas-boiler-broken" %}'>CHANGE</a></td>
</tr>
</table>
<h5>Which of the following control systems are present in this property?</h5>
<table>
    <tr>
        <td>Adjustable TRV controls on your radiators (Thermostatically Radiator Valves - turn valves that are positioned at one end of a radiator)</td>
        <td>{{ user_data.trvs_present|yesno|capfirst }}</td>
        <td><a href='{% url "questionnaire:heating-controls" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>One or more room thermostats (set the desired temperature in the room they are positioned in)</td>
        <td>{{ user_data.room_thermostat|yesno|capfirst }}</td>
        <td><a href='{% url "questionnaire:heating-controls" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>A central heating timer (a timer or programmer allows you to control when your heating and hot water comes on and when it goes off)</td>
        <td>{{ user_data.ch_timer|yesno|capfirst }}</td>
        <td><a href='{% url "questionnaire:heating-controls" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>A programmable central heating thermostat (combines time and temperature controls in a single unit)</td>
        <td>{{ user_data.programmable_thermostat|yesno|capfirst }}</td>
        <td><a href='{% url "questionnaire:heating-controls" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>A smart thermostat system (more advanced control systems for central heating that set temperature and timing and are connected to the internet)</td>
        <td>{{ user_data.smart_thermostat|yesno|capfirst }}</td>
        <td><a href='{% url "questionnaire:heating-controls" %}'>CHANGE</a></td>
    </tr>
</table>

prospector/templates/questionnaire/includes/icon_agree.html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="svg-icon">
    <path
        d="M7.493 18.75c-.425 0-.82-.236-.975-.632A7.48 7.48 0 016 15.375c0-1.75.599-3.358 1.602-4.634.151-.192.373-.309.6-.397.473-.183.89-.514 1.212-.924a9.042 9.042 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75 2.25 2.25 0 012.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H14.23c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23h-.777zM2.331 10.977a11.969 11.969 0 00-.831 4.398 12 12 0 00.52 3.507c.26.85 1.084 1.368 1.973 1.368H4.9c.445 0 .72-.498.523-.898a8.963 8.963 0 01-.924-3.977c0-1.708.476-3.305 1.302-4.666.245-.403-.028-.959-.5-.959H4.25c-.832 0-1.612.453-1.918 1.227z" />
</svg>

prospector/templates/questionnaire/includes/icon_control.html
<svg stroke-width="1.5" viewBox="0 0 24 24" fill="none"
    xmlns="http://www.w3.org/2000/svg" color="currentColor" class="svg-icon">
    <path
        d="M12 7.01l.01-.011M16 9.01l.01-.011M8 9.01l.01-.011M18 13.01l.01-.011M6 13.01l.01-.011M17 17.01l.01-.011M7 17.01l.01-.011M12 17l1-6M8.5 20.001H4A9.956 9.956 0 012 14C2 8.477 6.477 4 12 4s10 4.477 10 10c0 2.252-.744 4.33-2 6.001L15.5 20"
        stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
    <path d="M12 23a3 3 0 100-6 3 3 0 000 6z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
        stroke-linejoin="round"></path>
</svg>

prospector/templates/questionnaire/includes/icon_flame.html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="svg-icon">
    <path fill-rule="evenodd"
        d="M12.963 2.286a.75.75 0 00-1.071-.136 9.742 9.742 0 00-3.539 6.177A7.547 7.547 0 016.648 6.61a.75.75 0 00-1.152-.082A9 9 0 1015.68 4.534a7.46 7.46 0 01-2.717-2.248zM15.75 14.25a3.75 3.75 0 11-7.313-1.172c.628.465 1.35.81 2.133 1a5.99 5.99 0 011.925-3.545 3.75 3.75 0 013.255 3.717z"
        clip-rule="evenodd" />
</svg>

prospector/templates/questionnaire/includes/icon_house.html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="svg-icon">
    <path
        d="M19.006 3.705a.75.75 0 00-.512-1.41L6 6.838V3a.75.75 0 00-.75-.75h-1.5A.75.75 0 003 3v4.93l-1.006.365a.75.75 0 00.512 1.41l16.5-6z" />
    <path fill-rule="evenodd"
        d="M3.019 11.115L18 5.667V9.09l4.006 1.456a.75.75 0 11-.512 1.41l-.494-.18v8.475h.75a.75.75 0 010 1.5H2.25a.75.75 0 010-1.5H3v-9.129l.019-.006zM18 20.25v-9.565l1.5.545v9.02H18zm-9-6a.75.75 0 00-.75.75v4.5c0 .414.336.75.75.75h3a.75.75 0 00.75-.75V15a.75.75 0 00-.75-.75H9z"
        clip-rule="evenodd" />
</svg>

prospector/templates/questionnaire/includes/icon_person.html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="svg-icon">
    <path fill-rule="evenodd"
        d="M7.5 6a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM3.751 20.105a8.25 8.25 0 0116.498 0 .75.75 0 01-.437.695A18.683 18.683 0 0112 22.5c-2.786 0-5.433-.608-7.812-1.7a.75.75 0 01-.437-.695z"
        clip-rule="evenodd" />
</svg>

prospector/templates/questionnaire/includes/icon_phone.html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="svg-icon">
    <path fill-rule="evenodd"
        d="M1.5 4.5a3 3 0 013-3h1.372c.86 0 1.61.586 1.819 1.42l1.105 4.423a1.875 1.875 0 01-.694 1.955l-1.293.97c-.135.101-.164.249-.126.352a11.285 11.285 0 006.697 6.697c.103.038.25.009.352-.126l.97-1.293a1.875 1.875 0 011.955-.694l4.423 1.105c.834.209 1.42.959 1.42 1.82V19.5a3 3 0 01-3 3h-2.25C8.552 22.5 1.5 15.448 1.5 6.75V4.5z"
        clip-rule="evenodd" />
</svg>

prospector/templates/questionnaire/includes/icon_sun.html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="svg-icon">
    <path
        d="M12 2.25a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0V3a.75.75 0 01.75-.75zM7.5 12a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM18.894 6.166a.75.75 0 00-1.06-1.06l-1.591 1.59a.75.75 0 101.06 1.061l1.591-1.59zM21.75 12a.75.75 0 01-.75.75h-2.25a.75.75 0 010-1.5H21a.75.75 0 01.75.75zM17.834 18.894a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 10-1.061 1.06l1.59 1.591zM12 18a.75.75 0 01.75.75V21a.75.75 0 01-1.5 0v-2.25A.75.75 0 0112 18zM7.758 17.303a.75.75 0 00-1.061-1.06l-1.591 1.59a.75.75 0 001.06 1.061l1.591-1.59zM6 12a.75.75 0 01-.75.75H3a.75.75 0 010-1.5h2.25A.75.75 0 016 12zM6.697 7.757a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 00-1.061 1.06l1.59 1.591z" />
</svg>

prospector/templates/questionnaire/includes/vulnerabilities.html
</table>
<h4>Is anybody living in the property vulnerable to living in a cold home through one of the following? (select all that apply)</h4>
<table>
    <tr>
        <td>A cardiovascular condition (for example: heart condition, risk of stroke, high blood pressure etc.)</td>
        <td>{{ user_data.vulnerable_cariovascular|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>A respiratory condition (for example COPD or asthma)</td>
        <td>{{ user_data.vulnerable_respiratory|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>A mental health condition</td>
        <td>{{ user_data.vulnerable_mental_health|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>Disability</td>
        <td>{{ user_data.vulnerable_disability|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>Being over 65 years old</td>
        <td>{{ user_data.vulnerable_age|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>Being a young child (from new-born to school age)</td>
        <td>{{ user_data.vulnerable_children|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>Immunosuppression</td>
        <td>{{ user_data.vulnerable_immunosuppression|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>Being a pregnant</td>
        <td>{{ user_data.vulnerable_pregnancy|yesno:"Yes,No"|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
    <tr>
        <td>Any other conditions</td>
        <td>{{ user_data.vulnerable_comments|capfirst }}</td>
        <td><a href='{% url "questionnaire:vulnerabilities-general" %}'>CHANGE</a></td>
    </tr>
</table>
<table>