config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views


urlpatterns = [
    path("", include("prospector.apps.questionnaire.urls")),
    path("accounts/", include("prospector.apps.users.urls")),
    # Has to go above the main admin bit
    path(f"{settings.ADMIN_URL}django-rq/", include("django_rq.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

prospector/apps/questionnaire/urls.py
from django.urls import path

from .views import trail as views

app_name = "questionnaire"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("start", views.Start.as_view(), name="start"),
    path("name", views.RespondentName.as_view(), name="respondent-name"),
    path("role", views.RespondentRole.as_view(), name="respondent-role"),
    path(
        "consent",
        views.RespondentHasPermission.as_view(),
        name="respondent-has-permission",
    ),
    path(
        "will-to-contribute",
        views.WillToContribute.as_view(),
        name="will-to-contribute",
    ),
    path("company-name", views.CompanyName.as_view(), name="company-name"),
    path(
        "your-postcode", views.RespondentPostcode.as_view(), name="respondent-postcode"
    ),
    path("your-address", views.RespondentAddress.as_view(), name="respondent-address"),
    path("your-email", views.Email.as_view(), name="email"),
    path("phone-numbers", views.ContactPhone.as_view(), name="contact-phone"),
    path("occupant-name", views.OccupantName.as_view(), name="occupant-name"),
    path(
        "property-postcode", views.PropertyPostcode.as_view(), name="property-postcode"
    ),
    path("property-address", views.PropertyAddress.as_view(), name="property-address"),
    path("address-unknown", views.AddressUnknown.as_view(), name="address-unknown"),
    path("thank-you", views.ThankYou.as_view(), name="thank-you"),
    path("property-tenure", views.Tenure.as_view(), name="tenure"),
    path("consents", views.Consents.as_view(), name="consents"),
    path(
        "property-summary",
        views.PropertyMeasuresSummary.as_view(),
        name="property-measures-summary",
    ),
    path("occupants", views.Occupants.as_view(), name="occupants"),
    path(
        "means-tested-benefits",
        views.MeansTestedBenefits.as_view(),
        name="means-tested-benefits",
    ),
    path(
        "past-means-tested-benefits",
        views.PastMeansTestedBenefits.as_view(),
        name="past-means-tested-benefits",
    ),
    path("income", views.HouseholdIncome.as_view(), name="household-income"),
    path(
        "after-tax-income",
        views.HouseholdIncomeAfterTax.as_view(),
        name="household-income-after-tax",
    ),
    path("housing-costs", views.HousingCosts.as_view(), name="housing-costs"),
    path(
        "disability-benefits",
        views.DisabilityBenefits.as_view(),
        name="disability-benefits",
    ),
    path("child-benefit", views.ChildBenefit.as_view(), name="child-benefit"),
    path(
        "child-benefit-number",
        views.ChildBenefitNumber.as_view(),
        name="child-benefit-number",
    ),
    path(
        "child-benefit-claimant-type",
        views.ChildBenefitClaimantType.as_view(),
        name="child-benefit-claimant-type",
    ),
    path(
        "free-school-meals-eligibility",
        views.FreeSchoolMealsEligibility.as_view(),
        name="free-school-meals-eligibility",
    ),
    path(
        "vulnerabilities-general",
        views.VulnerabilitiesGeneral.as_view(),
        name="vulnerabilities-general",
    ),
    path("vulnerabilities", views.Vulnerabilities.as_view(), name="vulnerabilities"),
    path(
        "council-tax-reduction",
        views.CouncilTaxReduction.as_view(),
        name="council-tax-reduction",
    ),
    path("answers-summary", views.AnswersSummary.as_view(), name="answers-summary"),
    path("energy-advices", views.EnergyAdvices.as_view(), name="energy-advices"),
    path(
        "recommended-measures",
        views.RecommendedMeasures.as_view(),
        name="recommended-measures",
    ),
]

prospector/apps/users/urls.py
from django.urls import include
from django.urls import path

urlpatterns = [path("", include("django.contrib.auth.urls"))]

prospector/apps/crm/models.py
from django.db import models

from prospector.apps.questionnaire.models import Answers


class CrmState(models.TextChoices):
    SUCCESS = "SUCCESS", "Status Success"
    FAILURE = "FAILURE", "Status Failure"


class CrmResult(models.Model):
    answers = models.ForeignKey(Answers, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    state = models.CharField(
        max_length=32, choices=CrmState.choices, db_index=True, blank=True
    )
    result = models.JSONField(null=True)

prospector/apps/questionnaire/models.py
import uuid as uuid_lib
from typing import Optional

from django.db import models

from . import enums
from .utils import get_hug2_eligible_postcodes
from .utils import get_whlg_eligible_postcodes

SAP_BANDS = [
    enums.EfficiencyBand.D,
    enums.EfficiencyBand.E,
    enums.EfficiencyBand.F,
    enums.EfficiencyBand.G,
]

TAX_BANDS = [
    enums.CouncilTaxBand.A,
    enums.CouncilTaxBand.B,
    enums.CouncilTaxBand.C,
    enums.CouncilTaxBand.D,
]

EPC_BANDS = [
    enums.EfficiencyBand.D,
    enums.EfficiencyBand.E,
    enums.EfficiencyBand.F,
    enums.EfficiencyBand.G,
]

TENURES = [
    enums.Tenure.OWNER_OCCUPIED,
    enums.Tenure.RENTED_PRIVATE,
]

HUG2_ELIGIBLE_POSTCODES = get_hug2_eligible_postcodes()
WHLG_ELIGIBLE_POSTCODES = get_whlg_eligible_postcodes()


class Answers(models.Model):
    class Meta:
        verbose_name_plural = "answers"

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    uuid = models.UUIDField(
        db_index=True, default=uuid_lib.uuid4, editable=False, unique=True
    )
    short_uid = models.CharField(
        db_index=True,
        max_length=10,
        default=None,
        editable=False,
        unique=True,
        verbose_name="Client's unique reference number to be passed in email for reference purpose",
    )

    parity_object_id = models.CharField(
        max_length=20, editable=False, blank=True, null=True
    )

    """
    # "YOUR DETAILS"
    """

    terms_accepted_at = models.DateTimeField(blank=True, null=True)

    consented_callback = models.BooleanField(
        blank=True,
        null=True,
        verbose_name="Respondent consent to call or email them to offer advice and help",
    )

    consented_future_schemes = models.BooleanField(
        blank=True,
        null=True,
        verbose_name=(
            "Respondent consent to contact them in the future when there are relevant grants or programmes"
        ),
    )

    email = models.CharField(max_length=128, blank=True)

    first_name = models.CharField(verbose_name="First name", max_length=64, blank=True)
    last_name = models.CharField(verbose_name="Last name", max_length=64, blank=True)

    # The relationship of the respondent to the property
    respondent_role = models.CharField(
        max_length=24,
        choices=enums.RespondentRole.choices,
        blank=True,
        verbose_name="Relationship of respondent to property",
    )
    respondent_role_other = models.CharField(
        max_length=128,
        blank=True,
        verbose_name="Relationship of respondent to occupant",
    )

    company_name = models.CharField(
        max_length=128,
        blank=True,
        verbose_name="Landlord company name (if applicable)",
    )

    # Repondent address details are not used if respondent lives in the property
    respondent_address_1 = models.CharField(max_length=128, blank=True)
    respondent_address_2 = models.CharField(max_length=128, blank=True)
    respondent_address_3 = models.CharField(max_length=128, blank=True)

    respondent_udprn = models.CharField(
        max_length=10, blank=True, verbose_name="Respondent UDPRN from API"
    )

    respondent_postcode = models.CharField(max_length=16, blank=True)
    contact_phone = models.CharField(max_length=20, blank=True)
    contact_mobile = models.CharField(max_length=20, blank=True)

    respondent_comments = models.TextField(blank=True, null=True)

    source_of_info_about_pec = models.CharField(
        max_length=128,
        choices=enums.HowDidYouHearAboutPEC.choices,
        default=enums.HowDidYouHearAboutPEC.LABEL,
        blank=True,
    )

    """
    # PROPERTY DETAILS
    """

    occupant_first_name = models.CharField(
        verbose_name="Occupant first name", max_length=64, blank=True
    )
    occupant_last_name = models.CharField(
        verbose_name="Occupant last name", max_length=64, blank=True
    )
    property_address_1 = models.CharField(max_length=128, blank=True)
    property_address_2 = models.CharField(max_length=128, blank=True)
    property_address_3 = models.CharField(max_length=128, blank=True)
    property_postcode = models.CharField(max_length=16, blank=True)
    property_udprn = models.CharField(
        max_length=10, blank=True, verbose_name="Property UDPRN from API"
    )
    lower_super_output_area_code = models.CharField(max_length=50, blank=True)

    tenure = models.CharField(
        max_length=128,
        choices=enums.Tenure.choices,
        blank=True,
        verbose_name="Property ownership",
    )
    # UPRN is 12 digits, too big for a PositiveIntegerField
    uprn = models.CharField(max_length=120, blank=True, null=True)
    respondent_has_permission = models.BooleanField(null=True, blank=True)

    """
    # DATA SOURCE DETAILS
    """

    council_tax_band = models.CharField(
        max_length=1, choices=enums.CouncilTaxBand.choices, blank=True, null=True
    )
    sap_score = models.PositiveSmallIntegerField(blank=True, null=True)
    sap_band = models.CharField(
        max_length=1, choices=enums.EfficiencyBand.choices, blank=True, null=True
    )
    lodged_epc_score = models.PositiveSmallIntegerField(blank=True, null=True)
    lodged_epc_band = models.CharField(
        max_length=1, choices=enums.EfficiencyBand.choices, blank=True, null=True
    )
    multiple_deprivation_index = models.SmallIntegerField(blank=True, null=True)
    income_decile = models.SmallIntegerField(blank=True, null=True)

    # PROPERTY ENERGY PERFORMANCE DETAILS

    # All below fields are duplicated for user data and original data
    # If the user agrees with the presented data, the _orig field is left empty

    property_type = models.CharField(
        max_length=128,
        choices=enums.PropertyType.choices,
        blank=True,
    )

    property_attachment = models.CharField(
        max_length=128,
        choices=enums.PropertyAttachment.choices,
        blank=True,
    )

    property_construction_years = models.CharField(
        max_length=12,
        choices=enums.PropertyConstructionYears.choices,
        blank=True,
        null=True,
    )

    wall_construction = models.CharField(
        max_length=128,
        choices=enums.WallConstruction.choices,
        blank=True,
    )

    walls_insulation = models.CharField(
        max_length=128,
        choices=enums.WallInsulation.choices,
        blank=True,
    )

    roof_construction = models.CharField(
        max_length=128,
        choices=enums.RoofConstruction.choices,
        blank=True,
    )

    roof_insulation = models.CharField(
        max_length=128,
        choices=enums.RoofInsulation.choices,
        blank=True,
    )

    floor_construction = models.CharField(
        max_length=128, choices=enums.FloorConstruction.choices, blank=True
    )

    floor_insulation = models.CharField(
        max_length=128, choices=enums.FloorInsulation.choices, blank=True
    )

    glazing = models.CharField(
        max_length=128, choices=enums.Glazing.choices, blank=True
    )

    heating = models.CharField(
        max_length=128, choices=enums.Heating.choices, blank=True
    )

    main_fuel = models.CharField(
        max_length=128, choices=enums.MainFuel.choices, blank=True
    )

    boiler_efficiency = models.CharField(
        max_length=1, choices=enums.EfficiencyBand.choices, blank=True
    )

    controls_adequacy = models.CharField(
        max_length=128, choices=enums.ControlsAdequacy.choices, blank=True
    )

    heated_rooms = models.IntegerField(blank=True, null=True)
    t_co2_current = models.DecimalField(
        max_digits=3, decimal_places=1, blank=True, null=True
    )

    realistic_fuel_bill = models.CharField(max_length=9, blank=True, null=True)

    """
    # Top level household income assessment
    """

    adults = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Number of adults living in the property",
        choices=enums.OneToTen.choices,
    )
    children = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Number of children living in the property",
        choices=enums.OneToTenOrNone.choices,
    )

    seniors = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name="Number of seniors (over 60 years old) living in the property",
        choices=enums.OneToTenOrNone.choices,
    )

    household_income = models.IntegerField(
        null=True,
        blank=True,
        verbose_name="Total gross household income before tax",
    )

    household_income_after_tax = models.IntegerField(
        null=True,
        blank=True,
        verbose_name="Household income after tax",
    )

    means_tested_benefits = models.BooleanField(
        null=True,
        blank=True,
        verbose_name="Respondent receives means tested benefits",
    )
    past_means_tested_benefits = models.BooleanField(
        null=True,
        blank=True,
        verbose_name="Respondent received means tested benefits in the past 18 months",
    )
    disability_benefits = models.BooleanField(
        null=True,
        blank=True,
        verbose_name="Anyone in the house is receiving any disability related benefit",
    )
    child_benefit = models.BooleanField(
        null=True,
        blank=True,
        verbose_name="Anyone in the house is receiving child benefit",
    )
    child_benefit_number = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name=(
            "How many children child benefit is claimed for, or for which "
            "at least £21.80 per week of maintenance payments are made?"
        ),
        choices=enums.OneToFiveOrMore.choices,
    )
    child_benefit_claimant_type = models.CharField(
        max_length=10,
        null=True,
        blank=True,
        verbose_name=(

prospector/apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

prospector/templates/questionnaire/address_unknown.html
{% extends "questionnaire/base_question.html" %}
{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}


    <h2>
        We do not have data about your property
    </h2>

    <p>
        We do not have any valid data in our database about the property under the address you gave us.
        If you think the property might be eligible for retrofit grants, please leave your comments
        below and then click "Next" to submit them.
    </p>
{% endblock question_text %}

{% block form_content %}
    <div>
        <p>
            <label for="id_respondent_comments">
                Your comments:
            </label>
            <div class="comments-form-container">
                {{ form.respondent_comments }}
            </div>
        </p>
    </div>
{% endblock form_content %}

prospector/templates/questionnaire/base_question.html
{% extends "base.html" %}
{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block content %}

    <div class="progress">
        <label for="progress">progress</label>
        <progress id="progress" min="0" max="100" value="{{ percent_complete }}">(( percent_complete }}%</progress>
    </div>

    {% if prev_url %}
        <a href="{% url prev_url %}">&larr;&nbsp;Back to previous question</a>
    {% endif %}

    {% block question_text %}
        <h2 class="question-heading">
            {% if question_icon == "house" %}
                {% include "./includes/icon_house.html" %}
            {% elif question_icon == "flame" %}
                {% include "./includes/icon_flame.html" %}
            {% elif question_icon == "sun" %}
                {% include "./includes/icon_sun.html" %}
            {% else %}
                {% include "./includes/icon_person.html" %}
            {% endif %}
            {{ question_text|safe }}
        </h2>
    {% endblock question_text %}
    {% if messages %}
        <p>
            {% for message in messages %}
                {% if message.tags %}
                    <span class="{{ message.tags }}">{{ message }}</span>
                {% else %}
                    {{ message }}
                {% endif %}
            {% endfor %}
        </p>
    {% endif %}

    {% block question_supplement %}
        {% if question_supplement %}
            <div class="question-supplement">
                {{ question_supplement|safe }}
            </div>
        {% endif %}
    {% endblock question_supplement %}

    <form method="POST">
        {% csrf_token %}
        {% block form_content %}
            {% include 'questionnaire/dynamic_question_subview.html' %}
            {% if question_note %}
                <p class="note"><i>{{ question_note|safe }}</i></p>
            {% endif %}
        {% endblock form_content %}
        {% block nav_form %}
            <div class="nav-form">
                <button class="button">
                    Next&nbsp;&rarr;
                </button>
            </div>
        {% endblock nav_form %}
    </form>
{% endblock %}

prospector/templates/questionnaire/consent_to_proceed.html
{% extends "questionnaire/base_question.html" %}

{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2>{{ question_text }}</h2>
{% endblock question_text %}

{% block form_content %}
    <div class="govuk-checkboxes" data-module="govuk-checkboxes">
        <div class="govuk-checkboxes__item">
            <input
                type="checkbox"
                class="govuk-checkboxes__input"
                id="{{ form.field.auto_id }}_{{ value }}"
                name="{{ form.field.html_name }}"
                value="True"
                required
            >
            <label
                class="govuk-label govuk-checkboxes__label"
                for="{{ form.field.auto_id }}_{{ value }}">
                Accept
            </label>
            {% for error in form.field.errors %}
                <span class="input-error">Please accept to continue.</span>
            {% endfor %}
        </div>
    </div>
{% endblock form_content %}

prospector/templates/questionnaire/consents.html
{% extends "questionnaire/base_question.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2 class="question-heading">
        {% include "./includes/icon_agree.html" %}
        Your consent in how your data is used
    </h2>
    <p>Please tell us which of the following purposes you are happy for us to
        store and use your data for:</p>
{% endblock question_text %}

{% block form_content %}
    {{ form.consented_callback|as_crispy_field }}
    {{ form.consented_future_schemes|as_crispy_field }}
{% endblock form_content %}

prospector/templates/questionnaire/energy_advice.html
{% extends "questionnaire/base_question.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2 class="question-heading">
        {% include "./includes/icon_agree.html" %}
        Let us know if you need energy-related advice in addition to retrofit advice
    </h2>
    <p>Please tick the relevant boxes below:</p>
{% endblock question_text %}

{% block form_content %}
    {{ form.advice_needed_warm|as_crispy_field }}
    {{ form.advice_needed_bills|as_crispy_field }}
    {{ form.advice_needed_supplier|as_crispy_field }}
    <br>
    <br>
    {{ form.advice_needed_from_team|as_crispy_field }}
{% endblock form_content %}

prospector/templates/questionnaire/final_recommendations.html
{% extends "questionnaire/base_question.html" %}
{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
{% endblock question_text %}

{% block form_content %}

    <h2>Thank you, {{ full_name }}, for completing our online eligibility tool.</h2>

    <p>
        Your responses have been recorded and a copy has been sent to you by email for your records.
    </p>

    {% if measures %}

        {% include 'questionnaire/snippets/recommended_measures.html' %}

    {% endif %}

    {% if any_scheme_eligible %}
        {% include 'questionnaire/snippets/eligible_schemes.html' %}
    {% else %}
        {% include 'questionnaire/snippets/no_schemes_eligible.html' %}
    {% endif %}


    <p>Find out more about Future Fit and how we might be able to help you on the
        <a href="https://plymouthenergycommunity.com/residents/private-tenants">Plymouth Energy Community website</a>.
    </p>
{% endblock form_content %}

{% block nav_form %}
    {# remove default nav buttons #}
{% endblock nav_form %}

{% block call_us_line %}
    {# remove "call us" line #}
{% endblock call_us_line %}

prospector/templates/questionnaire/household_summary.html
{% extends "questionnaire/base_question.html" %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}Home upgrade eligibility: Income summary | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2>Your household's income:</h2>
{% endblock question_text %}

{% block form_content %}
    <ul>
        {% for adult in adult_incomes %}
            <li>
                <strong>{{ adult.name }}</strong>:
                £{{ adult.income|intcomma }}
            </li>
        {% endfor %}
    </ul>

    <p><strong>Total household income:</strong> £{{ calculated_income|intcomma }}</p>

    <p>
        <label>I confirm this is an accurate description of my household members' total annual income before tax</label>
        {{ form.confirm_or_amend_income|as_crispy_field }}
    </p>

    {% if calculated_income > 31000 %}
        <p>
            <label>Is the take home pay of your household after tax, national insurance, energy bills and housing costs less than £31,000?</label>
            {{ form.take_home_lt_31k_confirmation|as_crispy_field }}
        </p>
    {% endif %}
{% endblock form_content %}

prospector/templates/questionnaire/occupant_name.html
{% extends "questionnaire/base_question.html" %}
{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2 class="question-heading">
        {% include "./includes/icon_person.html" %}
        Who lives in the home?
    </h2>

    <p>Please tell us the name of the primary contact who occupies the home.</p>
{% endblock question_text %}

{% block form_content %}
    <p>
        <label for="id_occupant_first_name">
            First name
        </label>
        {{ form.occupant_first_name }}
        {{ form.occupant_first_name.errors }}
    </p>

    <p>
        <label for="id_occupant_first_name">
            Last name
        </label>
        {{ form.occupant_last_name }}
        {{ form.occupant_last_name.errors }}
    </p>
{% endblock form_content %}

prospector/templates/questionnaire/property_type.html
{% extends "questionnaire/base_question.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2 class="question-heading">
        {% include "./includes/icon_house.html" %}
        Property Type
    </h2>
{% endblock question_text %}

{% block form_content %}
    {% if form.data_correct %}
        <p>From the publicly available data on your property we think that this property is a
            <strong>{{ initial_attachment }} {{ initial_type|lower }}</strong>
        </p>

        {{ form.data_correct|as_crispy_field }}

        <div id="correction"{% if form.initial.data_correct != False %} style="display: none"{% endif %} class="govuk-form-group">
            <p> If not please select the correct option below:</p>
            <p>
                {{ form.property_attachment }}
                {{ form.property_attachment.errors }}
            </p>
            <p>
                {{ form.property_type }}
                {{ form.property_type.errors }}
            </p>
        </div>

    {% else %}
        <p>
            Please select the options that best describe your property
        </p>

        <p>
            {{ form.property_attachment }}
            {{ form.property_attachment.errors }}
        </p>
        <p>
            {{ form.property_type }}
            {{ form.property_type.errors }}
        </p>

    {% endif %}
{% endblock form_content %}

prospector/templates/questionnaire/respondent_role.html
{% extends "questionnaire/base_question.html" %}
{% load static %}

{% block question_text %}
    <h2 class="question-heading">
        {% include "./includes/icon_person.html" %}
        What is your relationship to the property?
    </h2>
{% endblock question_text %}

{% block form_content %}
    <div class="govuk-radios" data-module="govuk-radios">
        {% for value, label in form.respondent_role.field.widget.choices %}
            {% if value %}{# filter out the empty value #}
                <div class="govuk-radios__item">
                    <input
                        type="radio"
                        id="{{ form.respondent_role.auto_id }}_{{ value }}"
                        name="{{ form.respondent_role.html_name }}"
                        value="{{ value }}"
                        class="govuk-radios__input"
                        required
                        {% if value == form.respondent_role.data or value == form.respondent_role.initial %}checked{% endif %}>
                    <label
                        class="govuk-label govuk-radios__label"
                        for="{{ form.respondent_role.auto_id }}_{{ value }}">{{ label }}</label>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {{ form.respondent_role.errors }}

    <p class="note"><i>Please ensure that you have permission from the appropriate parties (landlord, tenant, owner occupier) to complete this form if you haven’t so far!</i></p>
    <div id="other-detail"{% if form.initial.respondent_role != "OTHER" %} style="display: none"{% endif %}>
        <p>
            <label for="id_respondent_role_other">
                Please describe your relationship to the occupant:
            </label>
            {{ form.respondent_role_other }}
            {{ form.respondent_role_other.errors }}
        </p>
    </div>
{% endblock form_content %}

prospector/templates/questionnaire/single_question.html
{% extends "questionnaire/base_question.html" %}
{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

prospector/templates/questionnaire/start.html
{% extends "questionnaire/base_question.html" %}

{% load static %}

{% block title %}Home upgrade eligibility: {{ title }} | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2>
        Use of your data
    </h2>
{% endblock question_text %}

{% block form_content %}
    <p>
        It’s not just the planet we want to protect, we also want to protect you and your data.
        We will store your data and information in accordance with data protection legislation.
    </p>
    <p>
        Our promise to you:
    </p>
    <p>
        We, PEC Trust, will record the information you give to us and use it to provide advice
        and support regarding upgrading your home. Your information may be shared with our
        funders for monitoring and evaluation purposes and, with your agreement, with our
        partners to provide services on your behalf such as surveying your home. For more
        information please see
        <a href="https://s3.eu-west-2.amazonaws.com/pec-assets-uk/files/Future-Fit/Privacy-Notice-Future-Fit.pdf">Future Fit Privacy Notice</a>
    </p>
    <div class="govuk-checkboxes" data-module="govuk-checkboxes">
        <div class="govuk-checkboxes__item">
            <input
                type="checkbox"
                class="govuk-checkboxes__input"
                id="{{ form.field.auto_id }}_{{ value }}"
                name="{{ form.field.html_name }}"
                value="True"
            >
            <label
                class="govuk-label govuk-checkboxes__label"
                for="{{ form.field.auto_id }}_{{ value }}">
                {{ question_text }}
            </label>
            {% for error in form.field.errors %}
                <span class="input-error">Please accept our privacy terms to continue.</span>
            {% endfor %}
        </div>
    </div>
{% endblock form_content %}

prospector/templates/questionnaire/thank_you.html
{% extends "questionnaire/base_question.html" %}

{% load static %}

{% block title %}Home upgrade eligibility: Thank you for completing this tool | Plymouth Energy Community{% endblock %}

{% block question_text %}
    <h2>Thank you for completing this tool</h2>

    <p>Read more about this project and how else we might be able to help you on the
        <a href="https://plymouthenergycommunity.com/residents/private-tenants"
            target="_blank" rel="noopener norefferer">
            Plymouth Energy Community website
        </a>.
    </p>

{% endblock %}

{% block nav_form %}
    {# remove default nav buttons #}
{% endblock nav_form %}